version: '3.8'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: db_shop_style
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

